-- 在 Supabase SQL Editor 中执行。仅保存自己的账号数据时，可先用匿名用户；正式上线建议开启登录。
create table if not exists public.training_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  module text not null,
  total integer not null check (total > 0),
  correct integer not null check (correct >= 0 and correct <= total),
  minutes integer not null check (minutes > 0),
  reason text,
  session_date date not null default current_date,
  start_time time,
  end_time time,
  note text,
  error_type text,
  created_at timestamptz not null default now()
);

alter table public.training_sessions add column if not exists session_date date not null default current_date;
alter table public.training_sessions add column if not exists start_time time;
alter table public.training_sessions add column if not exists end_time time;
alter table public.training_sessions add column if not exists note text;
alter table public.training_sessions add column if not exists error_type text;

create table if not exists public.study_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  detail text,
  done boolean not null default false,
  task_date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.question_book_records (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  book text not null,
  chapter text not null,
  module text not null,
  total integer not null check (total > 0),
  wrong integer not null check (wrong >= 0 and wrong <= total),
  error_content text,
  reason text,
  record_date date,
  created_at timestamptz not null default now()
);

alter table public.training_sessions enable row level security;
alter table public.study_tasks enable row level security;
alter table public.question_book_records enable row level security;

drop policy if exists "users manage own training sessions" on public.training_sessions;
drop policy if exists "public manages training sessions" on public.training_sessions;
drop policy if exists "shared path manages training sessions" on public.training_sessions;
drop policy if exists "users manage own study tasks" on public.study_tasks;
drop policy if exists "users manage own question book records" on public.question_book_records;

-- 个人使用模式：不要求登录，手机和平板共享同一份训练记录。
create policy "shared path manages training sessions" on public.training_sessions
  for all to anon, authenticated
  using (coalesce(current_setting('request.headers', true), '{}')::jsonb ->> 'x-cc-access' = 'ccday-7m4k2p')
  with check (coalesce(current_setting('request.headers', true), '{}')::jsonb ->> 'x-cc-access' = 'ccday-7m4k2p');
create policy "users manage own study tasks" on public.study_tasks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own question book records" on public.question_book_records
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
